/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchellingPanel.java
 *
 * Created on 05.07.2013, 10:45:13
 */

package ASwarm.grid;

import ASwarm.Agent;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author zaytsevid
 */
public abstract class GridPanel extends javax.swing.JPanel {
int N;
JPanel table[][];
    /** Creates new form SchellingPanel */
    public GridPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void init(int N, GridRelationship rel) {
        this.N = N;
        this.setSize(200, 200);
        this.setLayout(new GridLayout(N,N));
        table = new JPanel[N][N];
        for(int i = 0;i<N;i++)
            for(int j = 0;j<N;j++){
                JPanel p = new JPanel();
                paintPanel(rel.getAgent(i, j),p);
                p.setBorder(new LineBorder(Color.black,1));
                this.add(p);
                table[i][j] = p;
            }
    }

    public void moveAgs(Agent[] ags) {
        for(Agent a : ags){
            int x = ((GridRelationship)a.r).getX(a);
            int y = ((GridRelationship)a.r).getY(a);
            JPanel p = table[x][y];
            paintPanel(a, p);
        }
    }

    protected abstract void paintPanel(Agent agent, JPanel p);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
